version: "2"

run:
  timeout: 5m
  go: "1.24"

# Use default linters for golangci-lint v2 - don't specify enable/disable
# This avoids linter compatibility issues between versions
# CI uses golangci-lint v2.4.0, local may use v1.x - defaults work for both

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# Note: gofmt and goimports are formatters in v2, not linters
# Formatting is handled separately in CI pipeline steps