version: "2"

run:
  timeout: 5m
  go: "1.24"

# Minimal configuration using only core stable linters
# These should work in both golangci-lint v1 and v2
linters:
  enable:
    - errcheck     # Check for unchecked errors
    - govet        # Go vet tool  
    - ineffassign  # Detect ineffectual assignments
    - unused       # Check for unused code (replaces deadcode/varcheck)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# Note: Directory/file exclusions will be handled in CI args rather than config
# This minimal config focuses on linter compatibility between v1 and v2