run:
  timeout: 5m
  go: "1.18"

linters:
  disable:
    - varcheck
    - structcheck
    - gomnd
    - dupl
    - lll
    - godot
    - unparam
    - ineffassign
    - gosimple
    - stylecheck
    - staticcheck
  enable:
    - errcheck
    - gosec
    - gofmt
    - goimports
    - unused
    - govet
    - misspell
    - gocritic

issues:
  max-issues-per-linter: 0
  max-same-issues: 0