run:
  timeout: 5m
  go: "1.24"

# Minimal configuration using only core stable linters
# These should work in both golangci-lint v1 and v2
linters:
  enable:
    - errcheck     # Check for unchecked errors
    - govet        # Go vet tool  
    - ineffassign  # Detect ineffectual assignments
    - unused       # Check for unused code (replaces deadcode/varcheck)
  disable-all: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    # Skip external dependencies that cause issues
    - vendor
    # Skip blockchain directory due to ethereum client dependencies
    - internal/blockchain
  exclude-files:
    # Skip files that import problematic packages
    - ".*blockchain.*"
    - ".*ethclient.*"
  exclude:
    # Ignore ethereum client issues that are external dependencies
    - "could not load export data.*go-ethereum"
    - "no export data.*ethclient"

# This minimal config avoids deprecated linters and v2 compatibility issues